version: "3"
services:
   frontend:
     image: myrecipes-frontend:latest
     restart: unless-stopped
     build:
       context: frontend/.
     ports:
       - "127.0.0.1:8080:8080"
     extra_hosts:
       - "host.docker.internal:host-gateway"
     container_name: myrecipes-frontend
     volumes:
       - ./frontend:/app
       - /app/node_modules

  db:
    image: mariadb:latest
    restart: always
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: example #replaced with vault password
