version: "3"
services:
  frontend:
    image: staging_myrecipes-frontend:latest
    restart: unless-stopped
    build:
      context: frontend/.
    ports:
      - "127.0.0.1:9080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: staging_myrecipes-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    image: staging_myrecipes-backend:latest
    restart: unless-stopped
    build:
      context: backend/.
    ports:
      - "127.0.0.1:3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: staging_myrecipes-backend
    volumes:
      - ./backend:/app
      - /app/node_modules

  db:
    image: mariadb:latest
    restart: always
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      MARIADB_ROOT_PASSWORD: example #replaced with vault password
    container_name: staging_myrecipes-db
    volumes:
      - ./db:/var/lib/mysql
