version: "2.2"
services:
   frontend:
     image: myrecipes:latest
     restart: unless-stopped
     build:
       context: .
     ports:
       - "127.0.0.1:8080:8080"
     extra_hosts:
       - "host.docker.internal:host-gateway"
     container_name: myrecipes-frontend
     volumes:
       - .:/app
       - /app/node_modules
