services:
   web:
     image: vuejs:lts-bullseye
     restart: unless-stopped
     build:
       context: .
     ports:
       - 127.0.0.1:8080:8080
     container_name: vuejs
     volumes:
       - .:/app
       - /app/node_modules
